CREATE USER "CACHING" IDENTIFIED BY "root";

GRANT CREATE TYPE TO "CACHING";

GRANT CREATE TRIGGER TO "CACHING";

GRANT CREATE PROCEDURE TO "CACHING";

GRANT CREATE VIEW TO "CACHING";

GRANT CREATE SESSION TO "CACHING";

GRANT CREATE INDEXTYPE TO "CACHING";

GRANT CREATE SEQUENCE TO "CACHING";

GRANT CREATE PUBLIC SYNONYM TO "CACHING";

GRANT CREATE JOB TO "CACHING";

GRANT CREATE MATERIALIZED VIEW TO "CACHING";

GRANT CREATE SYNONYM TO "CACHING";

GRANT CREATE TABLE TO "CACHING";

ALTER USER "CACHING" QUOTA UNLIMITED ON USERS;
